title: AI-course
tagline: Capstone project 

author:
  name: Alani20220202
  url: https://www.facebook.com/Alani20220202

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
#theme: jekyll-theme-hydure
